### ISSUE TITLE
I will like to write about us for your blog

### ISSUE THREAD

**Issue by LINCOM011** [to-the-sun/amanuensis#6]
Hello, I have read and understand the concept of this work... So I will like to write about us for your blog if you give me the opportunity to do that... And I promise your will surely like it... Thanks and regards

**Comment by to-the-sun** [comment]
Sure, the more people who find out about this project the better. But what blog exactly are you talking about? Do you have one? Or do you mean my blog on Steemit?

**Comment by LINCOM011** [comment]
Your blog on steemit ... I can write about us for it ... Then still their should  be a website where people can easily download app and have  the full description of the app

**Comment by LINCOM011** [comment]
I can also write FAQ for the blog

**Comment by to-the-sun** [comment]
Alright, what sort of things would you want to write about? As far as an FAQ, you're the first to contact me about the project at all, so there haven't actually been any questions yet.

Have you tried the program out? I'd recommend that first and foremost. Maybe you would have some questions yourself.
