### ISSUE TITLE
i really want to contribute to this project

### ISSUE THREAD

**Issue by LINCOM011** [to-the-sun/amanuensis#8]
I want to contribute to this project , am good in writing private policy , about us , Faq and any other form that deal with writing... if you need anything on copywriting , i will be glad to help and contribute .. thanks and regards

**Comment by to-the-sun** [comment]
I'll keep you in mind, but I'm just not sure what I need written right now. What I need is just for people to use the program and then to write about their experience with it, submit suggestions, ask questions, etc.

**Comment by LINCOM011** [comment]
Can you  drop the link that I can use to download the app or program..
Cause I don't have access to the app.. Thanks

**Comment by to-the-sun** [comment]
On the main page, https://github.com/to-the-sun/amanuensis, click Clone or Download then Download Zip. You'll need Max 7 and Python 3.5 installed.

**Comment by to-the-sun** [comment]
There is no finished product yet. It's still a work in progress.

**Comment by to-the-sun** [comment]
Have you had a chance to tried out yet? What really does need to be written is the documentation for it. Especially instructions on getting it up and running. If you could write little snippets about your experience that would be most helpful. I suppose they could be compiled into a FAQ as well.
